spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pokerly?useUnicode=true&characterEncoding=utf8
    username: pokerly
    password: pokerly
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  application:
    name: pokerly

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: 'pokerly-example-secret-please-change-to-256-bit-at-least'
  access-token-validity-seconds: 3600 # 1시간
  refresh-token-validity-seconds: 1209600 # 14일

logging:
  level:
    root: INFO # 전역 로그 레벨
    org.springframework: DEBUG # 스프링 내부 동작
    org.hibernate.SQL: DEBUG # Hibernate가 실행하는 SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 바인딩 파라미터 로그
    com.rolling.pokerly: DEBUG # 우리 애플리케이션 패키지
