spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pokerly?useUnicode=true&characterEncoding=utf8
    username: pokerly
    password: pokerly
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  application:
    name: pokerly

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: 'pokerly-example-secret-please-change-to-256-bit-at-least'
  access-token-validity-seconds: 3600 # 1시간
  refresh-token-validity-seconds: 1209600 # 14일
